name = "subhub"
main = "worker.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "your-kv-id" },
  { binding = "TEMPLATE_CONFIG", id = "your-kv-id" }
]

[vars]
TEMPLATE_PASSWORD = "your-password" 